version: '2'
services:
    jhipsterfour-elasticsearch:
        container_name: jhipsterfour-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/jhipsterfour/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
