version: '2'
services:
    jhipsterfour-mysql:
        container_name: jhipsterfour-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/jhipsterfour/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipsterfour
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
